// NOTE THIS FILE IS AUTO GENERATED BY BUILD.ZIG
#define CPUFrame_tf_sp 0
#define CPUFrame_tf_lr 8
#define CPUFrame_tf_elr 16
#define CPUFrame_tf_spsr 24
#define CPUFrame_tf_esr 28
#define CPUFrame_tf_x 32
#define CPUFrame__size 272
