// NOTE THIS FILE IS AUTO GENERATED BY BUILD.ZIG
#define Thread_next 0
#define Thread_prev 8
#define Thread_proc 16
#define Thread_tid 24
#define Thread_stack_pointer 32
#define Thread_kernel_stack 48
#define Thread__size 4144
